spring.application.name=monitoramento

# Configuração H2 Database (modo file - dados persistem)
spring.datasource.url=jdbc:h2:file:./database/verdesmart-db.mv-db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Configuração JPA
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Console H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
